[package]
name = "keyless_wallet_recovery_solution"
version = "1.0.0"
authors = []

[addresses]
KeylessWalletRecoverySolution = '0x834064f1d50ec15f175940a04231a8b3cbaf746ff39df55595b715ff3acec81d'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
